"""auto_migration

Revision ID: 5989c689af7f
Revises: 
Create Date: 2026-05-30 02:55:59.466038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5989c689af7f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jurisdictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('coordinates_bounds', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['jurisdictions.id'], name=op.f('fk_jurisdictions_parent_id_jurisdictions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jurisdictions'))
    )
    op.create_index(op.f('ix_jurisdictions_code'), 'jurisdictions', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('language_preference', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('violations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('violation_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_violations'))
    )
    op.create_index(op.f('ix_violations_category'), 'violations', ['category'], unique=False)
    op.create_index(op.f('ix_violations_violation_code'), 'violations', ['violation_code'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('metadata_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('jurisdiction_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdictions.id'], name=op.f('fk_chat_sessions_jurisdiction_id_jurisdictions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_sessions'))
    )
    op.create_table('legal_sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('act_name', sa.String(length=255), nullable=False),
    sa.Column('section_number', sa.String(length=50), nullable=False),
    sa.Column('chapter', sa.String(length=100), nullable=True),
    sa.Column('clause', sa.String(length=50), nullable=True),
    sa.Column('explanation_text', sa.Text(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('jurisdiction_id', sa.UUID(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('gazette_reference', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('page_index', sa.String(length=255), nullable=False),
    sa.Column('keywords', postgresql.TSVECTOR(), nullable=True),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdictions.id'], name=op.f('fk_legal_sections_jurisdiction_id_jurisdictions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legal_sections'))
    )
    op.create_index('ix_legal_sections_keywords_gin', 'legal_sections', ['keywords'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_legal_sections_page_index'), 'legal_sections', ['page_index'], unique=False)
    op.create_index(op.f('ix_legal_sections_section_number'), 'legal_sections', ['section_number'], unique=False)
    op.create_table('traffic_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jurisdiction_id', sa.UUID(), nullable=False),
    sa.Column('order_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdictions.id'], name=op.f('fk_traffic_orders_jurisdiction_id_jurisdictions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_traffic_orders'))
    )
    op.create_index(op.f('ix_traffic_orders_order_type'), 'traffic_orders', ['order_type'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retrieval_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name=op.f('fk_chat_messages_session_id_chat_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_table('fine_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('violation_id', sa.UUID(), nullable=False),
    sa.Column('jurisdiction_id', sa.UUID(), nullable=False),
    sa.Column('legal_section_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_category', sa.String(length=100), nullable=False),
    sa.Column('first_offence_fine', sa.Float(), nullable=False),
    sa.Column('repeat_offence_fine', sa.Float(), nullable=True),
    sa.Column('imprisonment_months', sa.Integer(), nullable=True),
    sa.Column('license_suspension_months', sa.Integer(), nullable=True),
    sa.Column('compoundable', sa.Boolean(), nullable=False),
    sa.Column('surcharge_percent', sa.Float(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdictions.id'], name=op.f('fk_fine_schedules_jurisdiction_id_jurisdictions')),
    sa.ForeignKeyConstraint(['legal_section_id'], ['legal_sections.id'], name=op.f('fk_fine_schedules_legal_section_id_legal_sections')),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.id'], name=op.f('fk_fine_schedules_violation_id_violations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fine_schedules'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fine_schedules')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_traffic_orders_order_type'), table_name='traffic_orders')
    op.drop_table('traffic_orders')
    op.drop_index(op.f('ix_legal_sections_section_number'), table_name='legal_sections')
    op.drop_index(op.f('ix_legal_sections_page_index'), table_name='legal_sections')
    op.drop_index('ix_legal_sections_keywords_gin', table_name='legal_sections', postgresql_using='gin')
    op.drop_table('legal_sections')
    op.drop_table('chat_sessions')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_violations_violation_code'), table_name='violations')
    op.drop_index(op.f('ix_violations_category'), table_name='violations')
    op.drop_table('violations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_jurisdictions_code'), table_name='jurisdictions')
    op.drop_table('jurisdictions')
    # ### end Alembic commands ###
