"""initial_schema

Revision ID: 63f60d4f8558
Revises: 5989c689af7f
Create Date: 2026-05-30 16:59:58.627622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '63f60d4f8558'
down_revision: Union[str, Sequence[str], None] = '5989c689af7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legal_sections', sa.Column('embedding', Vector(384), nullable=True))
    op.create_index('ix_legal_sections_embedding_hnsw', 'legal_sections', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_legal_sections_embedding_hnsw', table_name='legal_sections', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_column('legal_sections', 'embedding')
    # ### end Alembic commands ###
